name: firebase_ui_oauth
description: Firebase UI widgets for authentication & OAuth
version: 1.4.17
homepage: https://github.com/firebase/FirebaseUI-Flutter/tree/master/packages/firebase_ui_oauth

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  desktop_webview_auth: ^0.0.14
  firebase_auth: ^4.15.3
  firebase_ui_auth: ^1.12.1
  firebase_ui_shared: ^1.4.1
  flutter_svg: ^2.0.9
  flutter:
    sdk: flutter

dependency_overrides:
  meta: ^1.9.1
  collection: ^1.17.1
  async: ^2.11.0
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

false_secrets:
  - "/example/**/google-services.json"
  - "/example/**/firebase_options.dart"
  - "/example/**/GoogleService-Info.plist"
  - "/example/lib/config.dart"

flutter:
